### ISSUE TITLE
curiousity bug

### ISSUE THREAD

**Issue by truedat101** [aratakileo/dlang#1]
What is your use case?  What code base exists in D that you need in python?  Speaking as a user of dlang.

**Comment by aratakileo** [comment]
I developed dlang in addition to my other library: pygex. Since pygex contains a GUI framework for pygame-ce, I found it necessary to integrate multilingual functionality. I came across the i18n, but I didn't like its structure, so dlang was created. However, it was never integrated into pygex, as pygex was abandoned some time after the creation of dlang. So there is no dlang-based codebase that I need in Python 🤷‍♂️
